import fs from "node:fs";
import js from "@eslint/js";
import globals from "globals";
import pluginVue from "eslint-plugin-vue";
import tseslint from "typescript-eslint";
import { importX } from "eslint-plugin-import-x";
import unusedImports from "eslint-plugin-unused-imports";
import eslintPluginPrettierRecommended from "eslint-plugin-prettier/recommended";

// Generated by unplugin-auto-import on first `vite` run.
const autoImportPath = new URL("./auto-import.json", import.meta.url);
const autoImports = fs.existsSync(autoImportPath) ? JSON.parse(fs.readFileSync(autoImportPath, "utf-8")) : { globals: {} };

const rules = {
  curly: "error",
  "no-console": ["warn", { allow: ["warn", "error", "info"] }],
  "no-debugger": "warn",
  "no-else-return": "error",
  "prefer-const": "error",
  "@typescript-eslint/no-unused-vars": "off",
  "@typescript-eslint/no-explicit-any": "error",
  "unused-imports/no-unused-imports": "error",
  "unused-imports/no-unused-vars": [
    "warn",
    {
      argsIgnorePattern: "^_",
      varsIgnorePattern: "^_",
      caughtErrorsIgnorePattern: "^_",
      args: "after-used",
      ignoreRestSiblings: true,
    },
  ],
  "padding-line-between-statements": [
    "error",
    { blankLine: "always", prev: "*", next: "multiline-const" },
    { blankLine: "always", prev: "*", next: "return" },
    { blankLine: "always", prev: "const", next: "export" },
    { blankLine: "always", prev: "multiline-block-like", next: "export" },
    { blankLine: "always", prev: "*", next: "multiline-expression" },
    { blankLine: "always", prev: "*", next: "if" },
    { blankLine: "always", prev: "multiline-expression", next: "*" },
    { blankLine: "always", prev: "if", next: "*" },
  ],
  "vue/multi-word-component-names": "off",
  "vue/html-self-closing": [
    "error",
    {
      html: { void: "always", normal: "never", component: "always" },
      svg: "always",
      math: "always",
    },
  ],
  "vue/attribute-hyphenation": ["error", "always"],
  "import-x/order": [
    "error",
    {
      groups: ["builtin", "external", "internal", "parent", "sibling", "index", "object"],
      "newlines-between": "ignore",
    },
  ],
};

export default tseslint.config(
  {
    ignores: ["**/dist/**", "**/node_modules/**", "**/coverage/**", "auto-imports.d.ts", "components.d.ts", "typed-router.d.ts", "auto-import.json"],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...pluginVue.configs["flat/essential"],
  eslintPluginPrettierRecommended,
  {
    files: ["**/*.vue"],
    languageOptions: {
      parserOptions: { parser: tseslint.parser },
    },
  },
  {
    files: ["**/*.{ts,vue,js}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: { ...globals.browser, ...globals.node, ...autoImports.globals, definePage: "readonly" },
    },
    plugins: { "import-x": importX, "unused-imports": unusedImports },
    settings: { "import-x/internal-regex": "^@/" },
    rules,
  }
);
