import { existsSync, globSync, readFileSync, writeFileSync } from "node:fs";
import { basename, relative } from "node:path";

import type { Plugin } from "vite";

// ponytail: mirrors unplugin-vue-components directoryAsNamespace naming, without collapseSamePrefixes
const componentName = (path: string) =>
  path
    .replace(/(\/index)?\.vue$/, "")
    .split("/")
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join("");

const exportLine = (path: string) =>
  path.endsWith(".vue") ? `export { default as ${componentName(path)} } from "./${path}";` : `export * from "./${path.replace(/\.ts$/, "")}";`;

const writeBarrel = (dir: string) => {
  const lines = globSync(`${dir}/**/*.{ts,vue}`)
    .filter((file) => !file.endsWith(".d.ts") && basename(file) !== "index.ts")
    .map((file) => exportLine(relative(dir, file)))
    .sort();
  const content = `// Auto-generated by the barrels vite plugin — do not edit.\n${lines.join("\n")}\n`;
  const out = `${dir}/index.ts`;

  if (!existsSync(out) || readFileSync(out, "utf8") !== content) {
    writeFileSync(out, content);
  }
};

export const barrels = (dirs: string[]): Plugin => ({
  name: "barrels",
  buildStart: () => dirs.forEach(writeBarrel),
  configureServer(server) {
    const onChange = (file: string) => {
      const dir = dirs.find((d) => relative(d, file).split("/")[0] !== "..");

      if (dir && basename(file) !== "index.ts") {
        writeBarrel(dir);
      }
    };
    server.watcher.on("add", onChange).on("unlink", onChange);
  },
});
