import { existsSync, globSync, readFileSync, writeFileSync } from "node:fs";
import { basename, relative } from "node:path";

import type { Plugin } from "vite";

const writeBarrel = (dir: string) => {
  const lines = globSync(`${dir}/**/*.ts`)
    .filter((file) => !file.endsWith(".d.ts") && basename(file) !== "index.ts")
    .map((file) => `export * from "./${relative(dir, file).replace(/\.ts$/, "")}";`)
    .sort();
  const content = `// Auto-generated by the barrels vite plugin — do not edit.\n${lines.join("\n")}\n`;
  const out = `${dir}/index.ts`;

  if (!existsSync(out) || readFileSync(out, "utf8") !== content) {
    writeFileSync(out, content);
  }
};

export const barrels = (dirs: string[]): Plugin => ({
  name: "barrels",
  buildStart: () => dirs.forEach(writeBarrel),
  configureServer(server) {
    const onChange = (file: string) => {
      const dir = dirs.find((d) => relative(d, file).split("/")[0] !== "..");

      if (dir && basename(file) !== "index.ts") {
        writeBarrel(dir);
      }
    };
    server.watcher.on("add", onChange).on("unlink", onChange);
  },
});
