export const ROUTES = {
  LOGIN: "/login",

  RIDER_HOME: "/rider",
  RIDER_CUSTOMERS: "/rider/customers",
  RIDER_TRIP_RETURN: (tripId: string) => `/rider/trip/${tripId}/return`,
  RIDER_DELIVER: (tripId: string, customerId?: string) => `/rider/trip/${tripId}/deliver${customerId ? `/${customerId}` : ""}`,

  CASHIER_HOME: "/cashier",
  CASHIER_SELL: "/cashier/sell",
  CASHIER_COLLECT: "/cashier/collect",
  CASHIER_RETURN_CONTAINER: "/cashier/return-container",
  CASHIER_TRIPS: "/cashier/trips",
  CASHIER_TRIPS_NEW: "/cashier/trips/new",
  CASHIER_TRIP_RECEIVE: (tripId: string) => `/cashier/trips/${tripId}/receive`,
  CASHIER_TRIP_RECONCILE: (tripId: string) => `/cashier/trips/${tripId}/reconcile`,
  CASHIER_COUNT: "/cashier/count",
  CASHIER_STOCK: "/cashier/stock",

  STAFF_LOGS: "/staff/logs",

  ME: "/me",
  ME_PAYSLIP: (payslipId: string) => `/me/payslips/${payslipId}`,

  OWNER_HOME: "/owner",
  OWNER_DIGEST: "/owner/digest",
  OWNER_APPROVALS: "/owner/approvals",
  OWNER_SALES: "/owner/sales",
  OWNER_TRIPS: "/owner/trips",
  OWNER_CUSTOMERS: "/owner/customers",
  OWNER_CUSTOMER: (customerId: string) => `/owner/customers/${customerId}`,
  OWNER_CONTAINERS: "/owner/containers",
  OWNER_INVENTORY: "/owner/inventory",
  OWNER_INVENTORY_CONSUMABLES: "/owner/inventory/consumables",
  OWNER_INVENTORY_MAINTENANCE: "/owner/inventory/maintenance",
  OWNER_INVENTORY_WATER_QUALITY: "/owner/inventory/water-quality",
  OWNER_MONEY: "/owner/money",
  OWNER_MONEY_EXPENSES: "/owner/money/expenses",
  OWNER_MONEY_CASH_SESSIONS: "/owner/money/cash-sessions",
  OWNER_PEOPLE: "/owner/people",
  OWNER_PEOPLE_EMPLOYEE: (employeeId: string) => `/owner/people/employees/${employeeId}`,
  OWNER_PEOPLE_PAYROLL: "/owner/people/payroll",
  OWNER_PEOPLE_PAYROLL_RUN: (runId: string) => `/owner/people/payroll/${runId}`,
  OWNER_PEOPLE_LOANS: "/owner/people/loans",
  OWNER_REPORTS: "/owner/reports",
  OWNER_REPORT: (report: string) => `/owner/reports/${report}`,
  OWNER_SETTINGS: "/owner/settings",
} as const;
